spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5332/readitlater
spring.datasource.username=postgres
spring.datasource.password=PortasFundos12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

#JWT
jwt.secret = "thisIsMysecregtfrdesww233eggtffeeddgkjjhhtdhttebd54ndhdhfhhhshs8877465sbbdd"
jwt.expiration=3600000

